Try
	
	
	//Execution time is approx - 8 minutes for each record
	
	Set Number_of_data_required to "1" --set the number to how much data you want to create
	Set Department to "QA" --Change the name of the department for whom the data needs to be created for e.g. change "QA" to "COT" for customer operations
	
	//*****Do not change anything below this line******************************************************************************************
	
	Repeat Number_of_data_required times  --
		Global LastName
		Global MemberType
		Global TestDataType
		
		
		//Setting up dynamic data
		put a..z into Letters -- Store the alphabet in a variable using a range
		put random(3,4) into NewNameLength -- Use the random function to randomly select a name length
		repeat NewNameLength times -- Repeat for each character in the new customer name
			put any item of letters after NewName -- Create a new name using random letters	
		end repeat
		
		
		Set MemberType to "-Student-AQ-" --Dont change this
		
		
		Set FirstName to Department & "-Data" --Dont change this
		Set LastName to Department & MemberType & NewName --Dont change this
		Set Email to "test@aat-test.org.uk" --Dont change this
		Set TestDataType to Department & MemberType --Dont Change this
		Log LastName
		
		Log "Creating a Student with AQ qual"
		
		Run "CommonBrowserFunctions" 's LaunchBrowserWithURL "iexplore","http://uatcrm.aat.org.uk/MasterTestData/main.aspx" //Launching MasterTestData CRM 
		
		Run "CreateNewContact" FirstName, LastName, Email
		
		Run "CommonCRMFunctions" 's NavigateFromTopMenuTo "Membership Applic"
		
		Run "CreateNewMembershipApplication" "Student" , "Student Registration 2014"
		
		Run "CommonCRMFunctions" 's NavigateFromTopMenuTo "Programme"
		
		Run "AddingAQ-ProgReg"
		
		Run "CommonCRMFunctions" 's NavigateFromTopMenuTo "Prerequisite"
		
		Run "ApprovingPreRequisites"
		
		Run "ApproveMembershipApplication"
		
		//Closing the browser
		Run "CommonBrowserFunctions" 's CloseBrowser
		
		
	End repeat
	
	Catch exception
	CaptureScreen	
	put the result
	Run "CommonBrowserFunctions" 's CloseBrowser	
	throw exception
	
End try

